name: CI

env:
  END_RESULT: "IT WORKS, AWESOME!"
  CUSTOM_GH_ACCESS_KEY: ${{ secrets.CUSTOM_GH_ACCESS_KEY }} # vcinc

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
        npm run format
    - name: Test
      run: npm run test
    - name: Print Refs
      run: |
        echo "refs: ${{ github.ref }}"
    - name: Print Envs
      run: echo "Result => ${{ env.END_RESULT }} CUSTOM ACCESS_KEY => ${{ CUSTOM_GH_ACCESS_KEY }}"
    - name: Run Script
      run: |
        echo "Print Envs from a shell script"
        chmod +x ../../scripts/experiment.sh
        ../../scripts/experiment.sh
